---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=4audrey
      - SUDO_PASSWORD=4audrey
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /appdata/vscode/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped